language="python"
print(language[1])
language="Learning python takes time"
print(language[1:17])
print(language[-2:12])
print(language[:])
print(language[2:])
print(language[8:])
print("Another method of character printing\n")
print("Take start with python"[2:14])
print("Take start with python"[::1])
print("Take start with python"[0:15:1])
print("\nOpposite string views:  \n")
print("Take start with python"[23::-1])
print("Take start with python"[-1::-1])
print("Take start with python"[::-1])
print("\nAnother step Argument tests\n")
print("Call911turbocarscollection"[0:23:2])
print("Call911turbocarscollection"[0::3])